### ISSUE TITLE
auth.cc does not compile with node v7.1.0

### ISSUE THREAD

**Issue by leolivier** [remotestorage/rs-serve#14]
Trying to compile auth.cc (in `make bindings`) and it fails with:
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/.nvm/versions/node/v7.1.0/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.38-v7+
gyp ERR! command "/home/pi/.nvm/versions/node/v7.1.0/bin/node" "/home/pi/.nvm/versions/node/v7.1.0/bin/node-gyp" "build"
gyp ERR! cwd /home/pi/apps/rs-serve/auth/bindings
gyp ERR! node -v v7.1.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

There are a lot of C++ errors, the first ones are:
```
../auth.cc:20:25: error: ‘Arguments’ does not name a type
 Handle<Value> Add(const Arguments& args) {
                         ^
In file included from /home/pi/.node-gyp/7.1.0/include/node/node.h:42:0,
                 from ../auth.cc:2:
/home/pi/.node-gyp/7.1.0/include/node/v8.h: In function ‘v8::Handle<v8::Value> Add(const int&)’:
/home/pi/.node-gyp/7.1.0/include/node/v8.h:882:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../auth.cc:21:15: error: within this context
   HandleScope scope;
               ^
../auth.cc:12:11: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
   if(args.Length() < n) {                                               \
           ^
../auth.cc:22:3: note: in expansion of macro ‘EXPECT_ARGS’
   EXPECT_ARGS(3);
   ^
../auth.cc:13:41: error: ‘New’ is not a member of ‘v8::String’
``` 
I don't really understand where the v8 stuff comes from as I'm using node 7.1.0 and node-gyp 3.4.0...
